INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (1,'Adana','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (2,'Adıyaman','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (3,'Afyonkarahisar','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (4,'Ağrı','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (5,'Amasya','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (6,'Ankara','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (7,'Antalya','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (8,'Artvin','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (9,'Aydın','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (10,'Balıkesir','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (11,'Bilecik','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (12,'Bingöl','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (13,'Bitlis','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (14,'Bolu','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (15,'Burdur','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (16,'Bursa','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (17,'Çanakkale','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (18,'Çankırı','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (19,'Çorum','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (20,'Denizli','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (21,'Diyarbakır','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (22,'Edirne','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (23,'Elazığ','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (24,'Erzincan','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (25,'Erzurum','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (26,'Eskişehir','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (27,'Gaziantep','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (28,'Giresun','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (29,'Gümüşhane','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (30,'Hakkari','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (31,'Hatay','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (32,'Isparta','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (33,'Mersin','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (34,'İstanbul','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (35,'İzmir','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (36,'Kars','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (37,'Kastamonu','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (38,'Kayseri','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (39,'Kırklareli','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (40,'Kırşehir','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (41,'Kocaeli','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (42,'Konya','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (43,'Kütahya','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (44,'Malatya','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (45,'Manisa','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (46,'Kahramanmaraş','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (47,'Mardin','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (48,'Muğla','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (49,'Muş','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (50,'Nevşehir','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (51,'Niğde','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (52,'Ordu','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (53,'Rize','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (54,'Sakarya','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (55,'Samsun','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (56,'Siirt','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (57,'Sinop','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (58,'Sivas','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (59,'Tekirdağ','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (60,'Tokat','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (61,'Trabzon','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (62,'Tunceli','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (63,'Şanlıurfa','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (64,'Uşak','Ege Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (65,'Van','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (66,'Yozgat','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (67,'Zonguldak','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (68,'Aksaray','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (69,'Bayburt','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (70,'Karaman','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (71,'Kırıkkale','İç Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (72,'Batman','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (73,'Şırnak','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (74,'Bartın','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (75,'Ardahan','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (76,'Iğdır','Doğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (77,'Yalova','Marmara Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (78,'Karabük','Karadeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (79,'Kilis','Güneydoğu Anadolu Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (80,'Osmaniye','Akdeniz Bölgesi');
INSERT INTO lokasyon(lokasyon_id,il,bolge) VALUES (81,'Düzce','Karadeniz Bölgesi');
